def parse_form_serialised_data_to_dict(dstr):
    """
    Parse a form data string generated by .serialise() in javascript to a dict of keys and values.
    :param dstr: Serialised Form Data String
    :return: Decoded dict of key-value pairs.
    """
    retr = {}
    dstra = dstr[1:-1].split("&")
    for dstr in dstra:
        values = dstr.split("=")
        if len(values) == 2:
            key, value = values
            retr[key] = value
    return retr